language: node_js

services:
  - mongodb
  - redis-server

before_install:
  - gem update --system
  - gem install sass
  - openssl aes-256-cbc -K $encrypted_622f743b98c0_key -iv $encrypted_622f743b98c0_iv -in .travis/warcraftlfg.enc -out .travis/warcraftlfg -d

install:
  - npm install -g mocha grunt-cli bower
  - npm install
  - mkdir logs


after_success:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis/warcraftlfg # this key should have push access
  - ssh-add .travis/warcraftlfg
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh warcraftlfg@warcraftlfg.com 'cd warcraft-lfg-testing;git pull;npm update;bower install;grunt prod'

notifications:
  slack: warcraftlfg:JV8vgwSfBUw1rSHCxlxlOUF3